server:
  port: 8888

spring:
  application:
    name: desifans-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sid532001/application-config.git
          clone-on-start: true
          default-label: main
          timeout: 10

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always