server:
  port: 8080

spring:
  application:
    name: desifans-api-gateway
  config:
    import: "configserver:http://localhost:8888"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Route for Config Server
        - id: config-server
          uri: lb://desifans-config-server
          predicates:
            - Path=/config/**
          filters:
            - StripPrefix=1
        
        # Route for Eureka Server
        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
